### ISSUE TITLE
Normalization of daily case numbers

### ISSUE THREAD

**Issue by davepypy** [covh/cov19de#4]
Hallo Andreas,

this is more of a question than an issue... Are the daily case numbers normalized to the number of tests?

Thanks,
Dave

**Comment by davepypy** [comment]
Or rather, would you consider including a normalized dataset using the test statistics form the RKI (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html)?

**Comment by covh** [comment]
No. But all this is open source, so feel free to fork and add that data yourself. 

However, be aware that nothing here is using RKI data, instead the data source is the CSV and google sheet of RiskLayer.

Closing this issue as the idea is out of scope. 

Have a good life.
